version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker-data/mongo:/data/db
    networks:
      - tdrive_network

  node:
    image: twakedrive/tdrive-node
    hostname: tdrive_node
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - tdrive_network

  fronend:
    image: twakedrive/tdrive-frontend
    environment:
      - DEV=production
      - SSL_CERTS=selfsigned
      - NODE_HOST=http://tdrive_node:4000
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node
    volumes:
      - ./docker-data/logs/nginx/:/var/log/nginx
      - ./docker-data/letsencrypt/:/etc/letsencrypt/
      - ./docker-data/drive-preview/:/tdrive-core/web/medias/
      - ./docker-data/uploads/:/tdrive-core/web/upload/
      - ./docker-data/ssl:/etc/nginx/ssl
    networks:
      - tdrive_network

networks:
  tdrive_network:
    driver: bridge

